### ISSUE TITLE
ModuleNotFoundError: No module named 'models.denoising_diffusion_pytorch'

### ISSUE THREAD

**Issue by novis10813** [MuhangTian/TimeDiff#2]
Great work! Now I'm trying to run the training process, but the error popped out.
It seems that there is no file named denoising_diffusion_pytorch` in the `model` folder

**Comment by MuhangTian** [comment]
Thank you for reaching out. Feel free to comment out the line `from models.denoising_diffusion_pytorch import Unet1D`. It is not used in TimeDiff, and I think it is a typo left in the script. I have updated the repo accordingly to solve this issue. Thank you for letting me know about this!
